version: '3'

services:
  svelte-app:
    environment:
      - DEBUG=true
    env_file: 
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
